apiVersion: apps/v1
kind: Deployment
metadata: 
  name: api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: us.gcr.io/challenge-pl/api
          env: 
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt_key
            - name: COOKIE_KEY
              valueFrom:
                secretKeyRef:
                  name: cookie-key
                  key: COOKIE_KEY
            - name: DB_HOST
              value: 'api-mongo-srv'
---
apiVersion: v1
kind: Service
metadata:
  name: api-srv
spec:
  selector:
    app: api
  ports:
    - name: api
      protocol: TCP
      port: 3000
      targetPort: 3000